apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - deployment.yaml
  - service.yaml
  - service-monitor.yaml
  - pvc.yaml

generators:
  - configmap-generator.yaml

labels:
  - pairs:
      app.kubernetes.io/name: splitwise-export
      app.kubernetes.io/part-of: splitwise-household-expenses
