apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: splitwise-export
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: splitwise-export
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
